CREATE TABLE IF NOT EXISTS `ACCOUNTS` (

    `ACCOUNT_ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DOCUMENT_NUMBER` varchar(20),
    `AVALIABLE_CREDIT_LIMIT` int NOT NULL,
    `REGISTRY_DATE` timestamp

);

CREATE TABLE IF NOT EXISTS `OPERATION_TYPES` (

    `OPERATION_TYPE_ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESCRIPTION` varchar(20),
    `REGISTRY_DATE` timestamp

);

CREATE TABLE IF NOT EXISTS `TRANSACTIONS` (
    `TRANSACTION_ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ACCOUNT_ID` int NOT NULL,
    `OPERATION_TYPE_ID` int NOT NULL,
    `AMOUNT` NUMERIC(20),
    `REGISTRY_DATE` timestamp

);

INSERT INTO `OPERATION_TYPES` (DESCRIPTION, REGISTRY_DATE) VALUES ('COMPRA A VISTA', now());

INSERT INTO `OPERATION_TYPES` (DESCRIPTION, REGISTRY_DATE) VALUES ('COMPRA PARCELADA', now());

INSERT INTO `OPERATION_TYPES` (DESCRIPTION, REGISTRY_DATE) VALUES ('SAQUE', now());

INSERT INTO `OPERATION_TYPES` (DESCRIPTION, REGISTRY_DATE) VALUES ('PAGAMENTO', now());